Various changes

diff --git a/doper-prod b/doper-prod
--- a/doper-prod
+++ b/doper-prod
@@ -1,10 +1,12 @@
 #!/bin/bash
 
-PNAMES="(prod|staging)"
-PORTS=("prod:301" "staging:302")
-CMDS="(up|down|restart|ps|logs|pull|images|stop|start)"
-DIR=/opt/docker/login
 export NAME=login
+PORTS=("prod:301" "staging:302")
+SRVS=("api" "lk" "edu")
+CMDS="(pull|up|down|ps|images|logs|restart|stop|start)"
+PNAMES="(prod|staging)"
+BASE="/opt/docker"
+export REGISTRY="docker.misis.ru:4443"
 
 ###############################################################################
 bin=$(basename "$0")
@@ -13,9 +15,9 @@ usage() {
   echo "  $bin $PNAMES $CMDS OPTS"
   echo
   echo "Examples:"
-  echo "  $bin prod up -d --build"
+  echo "  $bin staging pull"
+  echo "  $bin prod up -d"
   echo "  $bin prod restart edu"
-  echo "  $bin staging down"
   exit "$1"
 }
 
@@ -28,9 +30,14 @@ cmd="$1"
 echo "$cmd"|grep -Eq "^$CMDS$" || usage 1
 shift
 
-for p in "${PORTS[@]}"; do [ "${p%%:*}" = "$pname" ] && export PORT="${p##*:}"; done
+if [ "$cmd" = 'pull' ]; then
+  for a in "${SRVS[@]}"; do docker pull "$REGISTRY/$NAME/$a" --all-tags; done
+else
+  for p in "${PORTS[@]}"; do [ "${p%%:*}" = "$pname" ] && export PORT="${p##*:}"; done
+  if [ -z "$PORT" ]; then
+    echo "User not found"
+    exit 1
+  fi
 
-#docker-compose -f "/opt/docker/$pname/docker-compose.yml" "$cmd" $@
-#docker-compose -f "/opt/docker/login/docker-compose-$pname.yml" -p "$pname" "$cmd" $@
-#COMPOSE_PROJECT_NAME="$pname" docker-compose -f "/opt/docker/$pname/docker-compose.yml" "$cmd" $@
-COMPOSE_PROJECT_NAME="$pname" docker-compose -f "$DIR/docker-compose.yml" -f "$DIR/docker-compose.$pname.yml" "$cmd" $@
+  COMPOSE_PROJECT_NAME="$pname" docker-compose -f "$BASE/$NAME/docker-compose.yml" -f "$BASE/$NAME/docker-compose.$pname.yml" "$cmd" $@
+fi
